## 环境准备及导入数据

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Absenteeism_preprocessed.csv')
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

## 构建目标变量

In [5]:
# 如果缺勤时间大于该列的中位数，即为过度缺勤
target = np.where(df['Absenteeism Time in Hours'] > df['Absenteeism Time in Hours'].median(), 1, 0)
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
# 使用中位数设置目标值可以平衡数据集
target.sum() / target.shape[0]

0.45571428571428574

In [7]:
df['Excessive Absenteeism'] = target
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [8]:
# check point
data_with_target = df.drop(columns=['Day of the Week', 'Distance to Work', 'Daily Work Load Average', 'Absenteeism Time in Hours'], axis=1)
data_with_target.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                     289   33               30          0         2    1   
1                     118   50               31          0         1    0   
2                     179   38               31          0         0    0   
3                     279   39               24          0         2    0   
4                     289   33               30          0         2    1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## 特征工程

In [10]:
data_with_target.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet', 'Excessive Absenteeism'], dtype=object)

In [11]:
unscaled_features = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet']
unscaled_inputs = data_with_target[unscaled_features]

In [12]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  
0                       289   33               30          0         2    1  
1                       118   50               31          0         1    0  
2                       179   38               31          0         0    0  
3                       279   39               24          0         2    0  
4                       289   33               30          0         2    1  
..                      ...  ...              ...        ...       ...  ...  
695                     179   40               22          1         2    0  
696                     225   28               24          0         1    2  
697                     330   28               25          1         0    0  
698                     235   32               25          1         0    0  
699                     291   40               25          0         1    1  

[700 rows x 11 columns]

## 数据标准化

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
absenteeism_scaler = StandardScaler()

In [16]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler
class CustomScaler(BaseEstimator, TransformerMixin): 
    
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.columns = columns
        # Store the parameters as instance attributes
        self.copy = copy
        self.with_mean = with_mean
        self.with_std = with_std
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [17]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [18]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [19]:
columns_to_scale = [column for column in unscaled_inputs.columns.values if column not in columns_to_omit]
columns_to_scale

['Month Value',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pet']

In [20]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [21]:
# fit the data (calculate mean and standard deviation); they are automatically stored inside the object 
absenteeism_scaler.fit(unscaled_inputs)

/opt/anaconda3/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pet'])

In [22]:
# the scaled_inputs are now an ndarray, because sklearn works with ndarrays
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.568019   
696         1         0         0         0    -0.568019   
697         1         0         0         0    -0.568019   
698         0         0         0         1    -0.568019   
699         0         0         0         1    -0.568019   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

          Pet  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [23]:
scaled_inputs.shape

(700, 11)

## 数据集划分

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, target, random_state=20, train_size=0.8)

In [27]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [28]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


## 模型训练

In [30]:
# import the LogReg model
from sklearn.linear_model import LogisticRegression
# import the 'metrics' module, which includes important metrics we may want to use
from sklearn import metrics

In [31]:
model = LogisticRegression()

In [32]:
model.fit(x_train, y_train)

LogisticRegression()

In [33]:
predictions = model.predict(x_train)
predictions

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [34]:
predictions == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [35]:
# 手动计算精确度
accuracy = np.sum((predictions == y_train)) / y_train.shape[0]
accuracy

0.7767857142857143

In [36]:
# 调用函数计算精准度
model.score(x_train, y_train)

0.7767857142857143

## 模型解释

In [38]:
# 计算截距
intercept = model.intercept_[0]
intercept

-1.612058818637131

In [39]:
# 计算系数
model.coef_

array([[ 2.77145295,  0.93066915,  3.09778986,  0.81095274,  0.00784338,
         0.62550881, -0.17366788,  0.28863529, -0.23759979,  0.35765422,
        -0.27359133]])

In [40]:
features = list(scaled_inputs.columns.values)
features

['Reason_1',
 'Reason_2',
 'Reason_3',
 'Reason_4',
 'Month Value',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Education',
 'Children',
 'Pet']

In [41]:
summary_table = pd.DataFrame(columns=['features'], data=features)

In [42]:
summary_table['coefficients'] = np.transpose(model.coef_)

In [43]:
# 特征重要性表格
summary_table

features  coefficients
0                 Reason_1      2.771453
1                 Reason_2      0.930669
2                 Reason_3      3.097790
3                 Reason_4      0.810953
4              Month Value      0.007843
5   Transportation Expense      0.625509
6                      Age     -0.173668
7          Body Mass Index      0.288635
8                Education     -0.237600
9                 Children      0.357654
10                     Pet     -0.273591

In [44]:
# 将截距项加入表格
summary_table.index += 1
summary_table.loc[0] = ['Intercept', intercept]

In [45]:
summary_table = summary_table.sort_index()
summary_table

features  coefficients
0                Intercept     -1.612059
1                 Reason_1      2.771453
2                 Reason_2      0.930669
3                 Reason_3      3.097790
4                 Reason_4      0.810953
5              Month Value      0.007843
6   Transportation Expense      0.625509
7                      Age     -0.173668
8          Body Mass Index      0.288635
9                Education     -0.237600
10                Children      0.357654
11                     Pet     -0.273591

In [46]:
summary_table['odds_ratio'] = np.exp(summary_table['coefficients'])

In [47]:
summary_table

features  coefficients  odds_ratio
0                Intercept     -1.612059    0.199477
1                 Reason_1      2.771453   15.981838
2                 Reason_2      0.930669    2.536206
3                 Reason_3      3.097790   22.148945
4                 Reason_4      0.810953    2.250051
5              Month Value      0.007843    1.007874
6   Transportation Expense      0.625509    1.869197
7                      Age     -0.173668    0.840576
8          Body Mass Index      0.288635    1.334605
9                Education     -0.237600    0.788518
10                Children      0.357654    1.429971
11                     Pet     -0.273591    0.760643

In [48]:
# 按优势比降序排序
summary_table = summary_table.sort_values(by='odds_ratio', ascending=False)
summary_table

features  coefficients  odds_ratio
3                 Reason_3      3.097790   22.148945
1                 Reason_1      2.771453   15.981838
2                 Reason_2      0.930669    2.536206
4                 Reason_4      0.810953    2.250051
6   Transportation Expense      0.625509    1.869197
10                Children      0.357654    1.429971
8          Body Mass Index      0.288635    1.334605
5              Month Value      0.007843    1.007874
7                      Age     -0.173668    0.840576
9                Education     -0.237600    0.788518
11                     Pet     -0.273591    0.760643
0                Intercept     -1.612059    0.199477

## 测试模型

In [50]:
# 计算精准度
model.score(x_test, y_test)

0.7357142857142858

In [51]:
# 计算严重缺勤的概率
# 第一列为计算结果为0的概率，第二列为计算结果为1的概率
predicted_prob = model.predict_proba(x_test)
predicted_prob

array([[0.75474481, 0.24525519],
       [0.60921599, 0.39078401],
       [0.48308941, 0.51691059],
       [0.75777492, 0.24222508],
       [0.08374243, 0.91625757],
       [0.30576765, 0.69423235],
       [0.304347  , 0.695653  ],
       [0.11593645, 0.88406355],
       [0.74028784, 0.25971216],
       [0.75604656, 0.24395344],
       [0.50623046, 0.49376954],
       [0.19494548, 0.80505452],
       [0.0622781 , 0.9377219 ],
       [0.70496055, 0.29503945],
       [0.29598613, 0.70401387],
       [0.51955449, 0.48044551],
       [0.50564345, 0.49435655],
       [0.5085783 , 0.4914217 ],
       [0.36760692, 0.63239308],
       [0.06398808, 0.93601192],
       [0.73847776, 0.26152224],
       [0.75777492, 0.24222508],
       [0.48072183, 0.51927817],
       [0.47837739, 0.52162261],
       [0.22577443, 0.77422557],
       [0.74073908, 0.25926092],
       [0.51150857, 0.48849143],
       [0.87686551, 0.12313449],
       [0.23944739, 0.76055261],
       [0.75777492, 0.24222508],
       [0.

In [52]:
predicted_prob.shape

(140, 2)

In [53]:
# 只取第二列的计算结果，即严重缺勤的概率
predicted_prob[:, 1]

array([0.24525519, 0.39078401, 0.51691059, 0.24222508, 0.91625757,
       0.69423235, 0.695653  , 0.88406355, 0.25971216, 0.24395344,
       0.49376954, 0.80505452, 0.9377219 , 0.29503945, 0.70401387,
       0.48044551, 0.49435655, 0.4914217 , 0.63239308, 0.93601192,
       0.26152224, 0.24222508, 0.51927817, 0.52162261, 0.77422557,
       0.25926092, 0.48849143, 0.12313449, 0.76055261, 0.24222508,
       0.38855   , 0.71169728, 0.69771064, 0.49494357, 0.24222508,
       0.59774891, 0.26016392, 0.78069438, 0.43997582, 0.60636346,
       0.24179429, 0.49700761, 0.25835995, 0.40639195, 0.8073977 ,
       0.59952536, 0.71883372, 0.24308822, 0.24666618, 0.24136403,
       0.5017043 , 0.29321567, 0.69423235, 0.24449079, 0.82001991,
       0.39190275, 0.90627341, 0.26421695, 0.32126132, 0.32177361,
       0.70512513, 0.69572579, 0.26558883, 0.77627144, 0.24519155,
       0.24482075, 0.07526493, 0.26061618, 0.76236107, 0.29699697,
       0.25746103, 0.31516581, 0.88396409, 0.43881888, 0.59548

## 保存模型

In [55]:
import pickle

In [56]:
with open('model', 'wb') as file:
    pickle.dump(model, file)

In [57]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)